# Generated by Django 4.0.4 on 2022-05-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audioackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.package')),
                ('audio', models.FileField(upload_to='audio/')),
                ('medium', models.CharField(max_length=50)),
            ],
            bases=('main.package',),
        ),
        migrations.CreateModel(
            name='VideoPackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.package')),
                ('video', models.FileField(upload_to='videos/')),
                ('medium', models.CharField(max_length=50)),
            ],
            bases=('main.package',),
        ),
    ]
