# Generated by Django 4.0.4 on 2022-05-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_audioackage_videopackage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audioackage',
            new_name='AudioPackage',
        ),
    ]
